{
 "title": "Directory Services Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ldap_handler", "query": { "query": "label_values(ldap_handler)" } },
   { "name": "basedn", "query": { "query": "label_values(base_dn)" } },
   {
    "name": "public_basedn",
    "query": {
     "query": "label_values(ds_backend_entry_count{type=\"db\"}, base_dn)"
    }
   },
   {
    "name": "ds_job",
    "query": {
     "query": "label_values(ds_start_time_seconds, job)"
    }
   },
   {
    "name": "ds_instance",
    "query": {
     "query": "label_values(ds_start_time_seconds, instance)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(ds_disk_free_space_bytes, disk)"
    }
   },
   {
    "name": "domain",
    "query": {
     "query": "label_values(ds_replication_replica_remote_replicas_replayed_updates_seconds_count, domain_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall Load",
   "type": "gauge",
   "description": "This is the global average number of requests performed by the directory service.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ds_connection_handlers_ldap_requests_seconds_count[30s]))",
     "target": "sumSeries(*.ds.connection-handlers.ldap.requests.m1_rate)"
    }
   ]
  },
  {
   "title": "Requests in Queue",
   "type": "gauge",
   "description": "Number of requests in queue waiting to be processed",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_work_queue_requests_in_queue)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "gauge",
   "description": "The recent average of errors occurring in the service. These errors could be tied to client applications, invalid data, authentication failures...",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ds_connection_handlers_ldap_requests_failure_seconds_count[30s]))",
     "target": "sumSeries(*.ds.connection-handlers.ldap.requests.failures.m1_rate)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "description": "The total number of client connections opened against the whole directory service.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ds_current_connections)" }
   ]
  },
  {
   "title": "Max Receive Latency",
   "type": "gauge",
   "description": "This value represents the highest latency in receiving messages across all replicas, at each instant.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ds_replication_replica_remote_replicas_receive_delay_seconds)"
    }
   ]
  },
  {
   "title": "PingDS instances",
   "type": "timeseries",
   "description": "Numbers of DS, RS and proxies. Some instances may be combined DS/RS.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(up and ds_start_time_seconds)",
     "legendFormat": "Total number of PingDS instances"
    },
    {
     "expr": "sum(sum by (job) (up) and sum by (job) (ds_backend_entry_count{type=\"db\"}))",
     "legendFormat": "Number of DSs"
    },
    {
     "expr": "sum(sum by (job) (up) and sum by (job) (ds_backend_entry_count{base_dn=\"cn=changelog\"}))",
     "legendFormat": "Number of RSs"
    },
    {
     "expr": "sum(sum by (job) (up) and sum by (job) (ds_backend_entry_count{type=\"proxy\"}))",
     "legendFormat": "Number of Proxies"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "idelta(ds_connection_handlers_ldap_requests_failure_seconds_count[30s])",
     "legendFormat": "{{job}} {{instance}} - {{ldap_handler}} {{type}}"
    }
   ]
  },
  {
   "title": "Access Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load Averages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (job, instance, ldap_handler) (rate(ds_connection_handlers_ldap_requests_seconds_count{job=~\"$ds_job\",instance=~\"$ds_instance\",ldap_handler=~\"$ldap_handler\"}[1m]))",
     "legendFormat": "{{job}} {{instance}} {{ldap_handler}} m1_rate",
     "target": "*.ds.connection-handlers.ldap.requests.m1_rate"
    },
    {
     "expr": "sum by (job, instance, ldap_handler) (rate(ds_connection_handlers_ldap_requests_seconds_count{job=~\"$ds_job\",instance=~\"$ds_instance\",ldap_handler=~\"$ldap_handler\"}[5m]))",
     "legendFormat": "{{job}} {{instance}} {{ldap_handler}} m5_rate",
     "target": "*.ds.connection-handlers.ldap.requests.m5_rate"
    }
   ]
  },
  {
   "title": "Current response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job, instance, ldap_handler, type) (irate(ds_connection_handlers_ldap_requests_seconds_sum{job=~\"$ds_job\",instance=~\"$ds_instance\",ldap_handler=~\"$ldap_handler\"}[1m])) / sum by (job, instance, ldap_handler, type) (irate(ds_connection_handlers_ldap_requests_seconds_count{job=~\"$ds_job\",instance=~\"$ds_instance\",ldap_handler=~\"$ldap_handler\"}[1m]))",
     "legendFormat": "{{job}} {{instance}} - {{ldap_handler}} - {{type}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ds_replication_replica_remote_replicas_receive_delay_seconds",
     "legendFormat": "DS({{remote_server_id}}) → DS({{server_id}})"
    }
   ]
  },
  {
   "title": "Replay Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ds_replication_replica_remote_replicas_replay_delay_seconds",
     "legendFormat": "DS({{remote_server_id}}) → DS({{server_id}})"
    }
   ]
  },
  {
   "title": "Replayed updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(ds_replication_replica_remote_replicas_replayed_updates_seconds_count{job=~\"$ds_job\",instance=~\"$ds_instance\",domain_name=~\"$domain\"}[30s])",
     "legendFormat": "{{job}} {{instance}} {{domain_name}} last 30s"
    },
    {
     "expr": "rate(ds_replication_replica_remote_replicas_replayed_updates_seconds_count{job=~\"$ds_job\",instance=~\"$ds_instance\",domain_name=~\"$domain\"}[5m])",
     "legendFormat": "{{job}} {{instance}} {{domain_name}} last 5m"
    }
   ]
  },
  {
   "title": "Backend: $public_basedn",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "public_basedn",
   "targets": [
    {}
   ]
  },
  {
   "title": "$ds_instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 43 },
   "repeat": "ds_instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ds_backend_entry_count{base_dn=~\"$public_basedn\", instance=~\"$ds_instance\"}"
    }
   ]
  },
  {
   "title": "Disk free: ${disk}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "repeat": "disk",
   "targets": [
    {}
   ]
  },
  {
   "title": "${ds_instance}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 47 },
   "repeat": "ds_instance",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ds_disk_free_space_bytes{instance=~\"$ds_instance\", disk=~\"$disk\"}"
    }
   ]
  },
  {
   "title": "Health Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ds_jvm_memory_used_bytes{instance=~\"$ds_instance\"}",
     "legendFormat": "{{job}} {{instance}} JVM Total Memory Usage",
     "target": "*.ds.jvm-memory-usage.memory-usage.total.used"
    }
   ]
  },
  {
   "title": "Garbage Collections Time",
   "type": "timeseries",
   "description": "Time spent for garbage collections by minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ds_jvm_garbage_collector_g1_young_generation_time_seconds{instance=~\"$ds_instance\"}[1m])",
     "legendFormat": "{{job}} {{instance}} G1 young gen collections time m1_rate"
    },
    {
     "expr": "rate(ds_jvm_garbage_collector_g1_old_generation_time_seconds{instance=~\"$ds_instance\"}[1m])",
     "legendFormat": "{{job}} {{instance}} G1 old gen collections time m1_rate"
    },
    {
     "expr": "rate(ds_jvm_garbage_collector_zgc_major_cycles_time_seconds{instance=~\"$ds_instance\"}[1m])",
     "legendFormat": "{{job}} {{instance}} ZGC major cycles time m1_rate"
    },
    {
     "expr": "rate(ds_jvm_garbage_collector_zgc_minor_cycles_time_seconds{instance=~\"$ds_instance\"}[1m])",
     "legendFormat": "{{job}} {{instance}} ZGC minor cycles time m1_rate"
    }
   ]
  },
  {
   "title": "Garbage Collections: old gen memory after GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ds_jvm_memory_pools_g1_old_gen_used_after_gc_bytes",
     "legendFormat": "{{job}} {{instance}} G1 old gen used after GC"
    },
    {
     "expr": "ds_jvm_memory_pools_zgc_old_generation_used_after_gc_bytes",
     "legendFormat": "{{job}} {{instance}} ZGC old gen used after GC"
    }
   ]
  },
  {
   "title": "Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Certificate expiry in",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ds_certificates_certificate_expires_at_seconds - time()",
     "legendFormat": "{{job}} {{instance}} \"{{key_manager}}\", {{alias}}"
    }
   ]
  }
 ]
}